apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mocko.fullname" . }}-ui-config
data:
  nginx.conf: |
    worker_processes 4;

    events {
        worker_connections 1024;
    }

    http {
        include mime.types;
        default_type application/octet-stream;

        sendfile off;
        keepalive_timeout 65;

        gzip on;

        server {
            server_name _;
            root /usr/share/nginx/html/build;

            location / {
                try_files $uri /index.html;
            }

            location /_/ {
                proxy_pass "http://{{ include "mocko.fullname" . }}-api.{{ .Release.Namespace }}.svc.cluster.local:8080/";
            }
        }
    }
