apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mocko.fullname" . }}-ui
  labels:
    app.kubernetes.io/name: mocko-ui
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mocko-ui
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mocko-ui
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: mocko-ui
          image: "gabrielctpinheiro/mocko-ui:{{ .Values.version }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
# TODO probes
#          livenessProbe:
#            httpGet:
#              path: /
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 50m
              memory: 20Mi
          volumeMounts:
              - name: config-volume
                mountPath: "/etc/nginx/nginx.conf"
                subPath: "nginx.conf"
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "mocko.fullname" . }}-ui-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
