version: '2'

services:
  mocko:
    image: 'gabrielctpinheiro/mocko-proxy:1.6.4'
    environment:
      - PROXY_BASE-URI=
    ports:
      - '<%= port %>:8080'
    volumes:
      - './mocks:/home/mocko/mocks'
