site_name: Mocko Docs
repo_url: https://github.com/gabriel-pinheiro/mocko
edit_uri: tree/master/mocko-docs/docs
extra_css: ['extra.css']
theme: bootstrap4
nav:
  - Overview: index.md
  - Getting Started:
    - Standalone Mode: getting-started/standalone.md
    - Complete Stack: getting-started/complete.md
  - Templating: templating/index.md
