name: e2e tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Spinning services up
      run: cd e2e-tests; docker-compose up -d
    - name: Preparing tests
      run: cd e2e-tests; npm install
    - name: Testing
      run: cd e2e-tests; npm run test
